### ISSUE TITLE
Call to a member function getResponseStatusCode() on null

### ISSUE THREAD

**Issue by wiphi** [BugBuster1701/contao-cron-bundle#14]
**Umgebung**
Contao 4.6.6
Symfony 4.1.6
Contao Manager 1.0.4
Sonst eine ziemlich jungfräuliche Contao Installation mit frisch Installierten BackupDB und Cron-Bundle Package.

Ich bekomme beim Ausführen des Cronjobs für BackupDB mittels Symfony Route eine `getResponseStatusCode() on null` Exception. Meine Einstellungen:
<img width="552" alt="2018-10-04 21_48_26-scheduler die einstellungen dieses jobs bearbeiten - contao open source cms" src="https://user-images.githubusercontent.com/25878910/46499052-5c20e080-c81f-11e8-8e75-6c6c04a593d2.png">

und der zugehörige Stack Trace:
```
Error:
Call to a member function getResponseStatusCode() on null

  at vendor/bugbuster/contao-cron-bundle/src/Resources/contao/controllers/ContaoBackendController.php:186
  at BugBuster\Cron\ContaoBackendController->runRouteJob(object(Result))
     (vendor/bugbuster/contao-cron-bundle/src/Resources/contao/controllers/ContaoBackendController.php:130)
  at BugBuster\Cron\ContaoBackendController->runJob(object(Result))
     (vendor/bugbuster/contao-cron-bundle/src/Resources/contao/controllers/ContaoBackendController.php:92)
  at BugBuster\Cron\ContaoBackendController->runJobNow()
     (vendor/bugbuster/contao-cron-bundle/src/Controller/BackendController.php:26)
  at BugBuster\CronBundle\Controller\BackendController->startJobNowAction()
     (vendor/symfony/http-kernel/HttpKernel.php:149)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:66)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:188)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:79)
```
Ich vermute, dass es irgendwas mit Symfony 4 zu tun haben könnte, nur leider fehlt mir gerade etwas die Zeit um selbst zu debuggen. Solltest Du noch Informationen benötigen, wie einen erweiterten Symfony Stack Trace, stehe ich gerne bereit.

**Comment by BugBuster1701** [comment]
Normalerweise sollte dort folgender Text kommen:
_Das PHP-Flag "allow_url_fopen" ist nicht gesetzt.
Die PHP cURL-Erweiterung ist nicht verfügbar.
Eins davon ist notwendig._

Das der Text nicht kommt ist mein Problem, das ich keine Verbindung aufbauen kann, wegen den Problemen oben, ist Deins.


@BugBuster1701 
https://github.com/BugBuster1701/contao-cron-bundle/blob/8bdf742a3abcc21d0f5f32448d717275c3f3e37c/src/Resources/contao/controllers/ContaoBackendController.php#L186
https://github.com/BugBuster1701/contao-cron-bundle/blob/8bdf742a3abcc21d0f5f32448d717275c3f3e37c/src/Resources/contao/controllers/ContaoBackendController.php#L203
Dort ist $request = null, daher fest "500" einsetzen.

**Comment by wiphi** [comment]
Ok alles klar, danke! Ich schau mal ob ich in der php.ini des Webhosters da was drehen kann. `allow_url_fopen` sollte denk ich gehen.

Edit: `allow_url_fopen` ist aktiviert und auch `curl` ist verfügbar.

Der Fehler muss also wo anders liegen...

**Comment by BugBuster1701** [comment]
Mit der 1.3.2 müssten jetzt Meldungen kommen, hoffe ich.

**Comment by wiphi** [comment]
`::500::The "httplug.client.my_curl" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.`

Ist das der erhoffte Fehler?

**Comment by BugBuster1701** [comment]
https://github.com/BugBuster1701/contao-cron-bundle/issues/17

**Comment by BugBuster1701** [comment]
In der 1.3.3 sollte es nun funktionieren.
