### ISSUE TITLE
Scheduler is not running every time

### ISSUE THREAD

**Issue by darkojic** [BugBuster1701/contao-cron-bundle#22]
Hi,

I have three cron jobs, two that run only once in a day. They are performing just fine.
And the third that runs at weekend in some period for two hours - every minute.

But that 3rd job is not executing every time. Sometimes it executes, and then stops, until I run it manually. Then it works for couple of times, and then again stop. When I reload Scheduler page in BackEnd, it runs, but when I am not there, it runs sometimes, but usually stops after several times.

I think that everything is set as suposed to be. 

Illustration attached.

What I did wrong or misunderstood?

![Scheduler - Contao Open Source CMS - Opera](https://user-images.githubusercontent.com/42218572/63256913-ed9f1280-c278-11e9-9310-975b206d0a80.jpg)

Here is system log about job running. It could be seen that it hasn't ran every minute, as scheduled.
![- Contao Open Source CMS - Opera](https://user-images.githubusercontent.com/42218572/63266975-63af7380-c291-11e9-8a9a-5a24a4baaf87.jpg)

**Comment by darkojic** [comment]
Here is system log data about job running. It could be sen that it hasn't ran every minute, as schedul
![- Contao Open Source CMS - Opera](https://user-images.githubusercontent.com/42218572/63266975-63af7380-c291-11e9-8a9a-5a24a4baaf87.jpg)
ed.

**Comment by BugBuster1701** [comment]
Why a job is stopped I cannot say, neither the extension nor Contao does this. But PHP will do this if the script runs too long.

Is the job 3 a relative path of a PHP script, a symfony route, or a URL?

**Comment by darkojic** [comment]
Well, it seems to me that it acts like "poor-man" cron job, executing only when it is triggered on webpage? Maybe it should work like that, and I did not understood it?

**Comment by BugBuster1701** [comment]
Yes, by default, the scheduler is triggered on every backend page update, like "poor-man" cron.

If you have a server where cron jobs can be set up, you can use this system cron to trigger the cron bundle extension.  The advantage is that the cron job will be started at the scheduled time, even if nobody is accessing the website. 

Example for the entry in the "crontab:
`* * * * * wget -t 1 -O - http://www.example.com/bbcron/startjobs >/dev/null 2>&1`

**Comment by darkojic** [comment]
I have paid/shared hosting where provider has not gave us permission to cron job tasks. 

But, okay, the most important is that it's not a bug, rather my missunderstanding.
I will close the issue.

Thank you for explanation.
