### ISSUE TITLE
Keine Installation mit Contao 4.9.*

### ISSUE THREAD

**Issue by dp-designpilot** [BugBuster1701/contao-cron-bundle#30]
Hallo BugBuster
Laut Packagist ist die Version des Contao Cron Bundle bis version <5.0 lauffähig, ich kann aber die aktuelle Version nicht installieren (beim Test über den Contao Manager hat es mir einige Fehler ausgegeben)

Problem 1
    - Conclusion: don't install bugbuster/contao-cron-bundle 1.3.7
    - Conclusion: don't install bugbuster/contao-cron-bundle 1.3.6
    - Conclusion: don't install bugbuster/contao-cron-bundle 1.3.5
    - Conclusion: don't install bugbuster/contao-cron-bundle 1.3.4
    - Conclusion: don't install bugbuster/contao-cron-bundle 1.3.3
    - Conclusion: don't install bugbuster/contao-cron-bundle 1.3.2
    - Conclusion: don't install bugbuster/contao-cron-bundle 1.3.1
    - Installation request for symfony/options-resolver (locked at v5.1.0) -> satisfiable by symfony/options-resolver[v5.1.0].
    - Installation request for bugbuster/contao-cron-bundle ^1.3 -> satisfiable by bugbuster/contao-cron-bundle[1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7].
    - Conclusion: don't install php-http/httplug 2.1.0
    - bugbuster/contao-cron-bundle 1.3.0 requires php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1].
    - php-http/guzzle6-adapter v1.1.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - php-http/guzzle6-adapter v1.1.1 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - Can only install one of: php-http/httplug[v1.0.0, 2.1.0].
    - Can only install one of: php-http/httplug[v1.1.0, 2.1.0].
    - Installation request for php-http/httplug (locked at 2.1.0) -> satisfiable by php-http/httplug[2.1.0].

[2244.8MiB/42.98s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[466.3MiB/44.54s] Memory usage: 466.25MB (peak: 2245.72MB), time: 44.56s.
[466.2MiB/44.54s] Finished Composer Cloud resolving.

Kannst Du dazu was sagen ?

**Comment by BugBuster1701** [comment]
Du musst dazu ein vollständiges Update aller Pakete durchführen.
Im Manager erst alles zum Update auswählen (Pakete aktualisieren), aber dann nicht auf ausführen, sondern nun über Pakete mein Bundle suchen und auswählen.
Jetzt kann mit Ausführen alles gemeinsam installiert werden und wo nötig ein Update/Downgrade ausgeführt werden.

**Comment by dp-designpilot** [comment]
Hat alles so funktioniert wie Du gesagt hast
