### ISSUE TITLE
Ausführung nur bei LogIn

### ISSUE THREAD

**Issue by Benjamin-Scherf** [BugBuster1701/contao-cron-bundle#34]
Hallo,

ich habe die Extension installiert um ein Autobackup laufen zu lassen. Es soll alle 8 Stunden ein Backup des Systems durchgeführt werden. Für den Backup-Vorgang nutze ich die Extension "Datenbanksicherung" von Hagen Klemp. Diese stellt einen Frontendlink zur Verfügung. https://meinedomain.de/BackupDB/autobackup.

Ich habe einen Job angelegt mit dem Link und der Einstellung 1 /*8 * * *.

Leider startet der Job nicht alle 8 Stunden automatisch. Stattdessen beobachte ich, dass der Job startet wenn ich mich nach einer gewissen Abwesenheitszeit wieder in das Backend einlogge.

Zusatzfrage: Wie muss die Zeiteinstellung gesetzt werden, dass der Job alle 8 Stunden um 0:00, 8:00, 16:00 Uhr ausgeführt wird.

Vielen Dank

**Comment by BugBuster1701** [comment]
Die Erweiterung ist kein echter Crontab Ersatz, er biete nur die Möglichkeit an, bei regelmäßigen Seitenaufrufen das nachzubilden.
Wenn also nach 0:00 Uhr / 8:00 Uhr / 16:00 Uhr einige Seitenaufrufe erfolgen, dann kommt es zur Auslösung.
Siehe: [Auslösen des Schedulers](https://de.contaowiki.org/Cron-Bundle#Ausl.C3.B6sen_des_Schedulers)

Wurde ein Frontend Modul angelegt und im Layout eingebunden?
