### ISSUE TITLE
URL-Length, get paramters and timeout

### ISSUE THREAD

**Issue by bwl21** [BugBuster1701/contao-cron-bundle#40]
**Describe the bug**

Not sure if it is a bug or a feature request

I try to schedule an importer and find

* Limitation of URL to 100 characters is not sufficient in particular if we pass some arguments as get vars
* get vars are not submitted to the the website which is called by the scheduler
* I get a timeout after a few seconds, the importer runs for about 30 seconds

**Affected version(s)**
 -  Contao Version [e.g. 4.9.5]

Version 1.4.5 (07.09.2020, 23:58)
contao 4.9.5

**To Reproduce**

sorry, I cannot publish our enviroment here. If needed I will setup a test case, but maybe the limitations are intended - which makes this report to a feature request ...

**Expected behavior**

* no practical limt for the length of url
* forward the get parameters to the website if cronjob is a URL
* make the timeout adjustable.

**Additional context**

**Comment by BugBuster1701** [comment]
In version 1.4.6 the URL field was increased to 1000 characters. Database update is necessary after the update.
GET parameters should now also work.

**Comment by bwl21** [comment]
Thanks for your quick action to take it up. I see that #41 is some effort. could you please set the value to 300 until #41 is fixed.
