### ISSUE TITLE
make the timeout adjustable.

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/contao-cron-bundle#41]
see #40 

_Job runtimes over 5 seconds are not useful in a web page request. But the specification of the runtime has been requested several times._

**Comment by BugBuster1701** [comment]
- [x] DCA: Expertenbereich und Timeout Feld
- [x] ContaoBackendController
- [x] ContaoFrontendController
- [x] CronRequest
- [x] Sprachdateien
- [x] Handbuch

**Comment by bwl21** [comment]
I propose that in the meantime you set the default to 300 seconds

**Comment by bwl21** [comment]
Hi BugBuster, 
thanks for fixing this. 

Sorry, I use this channel to ask for an advice. In another project running on contao 4.4.1, I am using scheduler 1.3.8 (the last version compatible with contao 4.4.). I have created an entry which calls a php-script. It worked exactly once. If I now start the job manually, it does nothing. the result looks like this

```
[23-Sep-2020 06:33:33] Running scheduler job manually
::
[23-Sep-2020 06:33:33] Manually scheduler job complete
```
It seems that it does not start the php script. I have no clue how to track this down. There is no entry in the Logger nor in the logfiles.

It works If I invoke the script via https:

could you give me a hint?

**Comment by BugBuster1701** [comment]
This is the correct output for a job as file.
Example of my demo job "purge logs":
![PurgeJobLog](https://user-images.githubusercontent.com/1218809/94290968-413f5d80-ff5b-11ea-9c76-e359672eaca1.png)

All output of your script (echo "...") would be displayed after the "::", if there is any.
So you can add debug lines to your script.

Or have a look here how I enter messages into the system log:
https://docs.contao.ninja/books/user-guide_cron_bundle/en/userdefined-cronjob-scripts/#example-script
