### ISSUE TITLE
AutoBackupDB triggered multiple times

### ISSUE THREAD

**Issue by johannes-bittner** [BugBuster1701/contao-cron-bundle#44]
**Describe the bug**
The script seems to trigger AutoBackupDB multiple times (varies)

**Affected version(s)**
 - Version [1.5.0]
 -  Contao Version [4.9.9]

**To Reproduce**
1. Job defined as URL [e.g. https://www.domain.de/BackupDB/autobackup?mysecretparameter]
2. Hour 2, minute/day/month/weekday *, time limit 5 sec
3. Mailing of the backup is activated
4. On first logon of the day, I receive between 2-10 mails/backups

**Expected behavior**
Only one mailing

**Comment by BugBuster1701** [comment]
Is it possible that the backup takes longer than 5 seconds?
Then it is defined as "not finished" and restarted on the next page request.

**Comment by johannes-bittner** [comment]
Yes, I tried this - setting a higher timeout solves the issue.
