### ISSUE TITLE
No installation possible under Contao Version 5.3.15

### ISSUE THREAD

**Issue by csaeum** [BugBuster1701/contao-cron-bundle#53]
**Describe the bug**
Just wanted to install this under the above mentioned version but unfortunately no possibility

**Affected version(s)**
 - 1.7.0 (veröffentlicht am 1. September 2024 um 15:24)
 - Contao Version 5.3.15
 - PHP Version 8.3.8

**To Reproduce**
In contao-manager:

**Expected behavior**
`  Problem 1
    - Root composer.json requires bugbuster/contao-cron-bundle ^1.7 -> satisfiable by bugbuster/contao-cron-bundle[1.7.0].
    - bugbuster/contao-cron-bundle 1.7.0 requires contao/core-bundle >=5.4.0,<5.7.0 -> found contao/core-bundle[5.4.0, 5.4.1, 5.4.2, 5.4.3] but these were not loaded, likely because it conflicts with another require.`

**Comment by BugBuster1701** [comment]
`bugbuster/contao-cron-bundle 1.7.0 requires contao/core-bundle >=5.4.0,<5.7.0`
This Version is only for Contao 5.4.
For Contao 5.3 use 1.6.0.
